### ISSUE TITLE
Buils fails with gcc 9.3

### ISSUE THREAD

**Issue by dominik-handler** [NVIDIA-Genomics-Research/GenomeWorks#660]
Hi,

I tried to build racon and as part of it genomeworks is built. Per default I had gcc9.3 installed and the build of GenomeWorks failed. When I tried to build it separately from racon I had the same problem. I was able to install it nicely when switching back to gcc8. 

I got this error message:
09:55:56  [ 36%] Building CXX object cudaaligner/CMakeFiles/cudaaligner.dir/src/cudaaligner.cpp.o
09:55:56  [ 36%] Building CXX object cudaaligner/CMakeFiles/cudaaligner.dir/src/aligner_global_ukkonen.cpp.o
09:55:56  [ 38%] Building CXX object cudaaligner/CMakeFiles/cudaaligner.dir/src/aligner.cpp.o
09:55:56  [ 38%] Building CXX object cudaaligner/CMakeFiles/cudaaligner.dir/src/aligner_global.cpp.o
09:55:56  [ 38%] Building CXX object cudaaligner/CMakeFiles/cudaaligner.dir/src/alignment.cpp.o
09:55:56  [ 39%] Building CXX object cudaaligner/CMakeFiles/cudaaligner.dir/src/alignment_impl.cpp.o
09:55:56  [ 39%] Building CXX object cudaaligner/CMakeFiles/cudaaligner.dir/src/aligner_global_myers.cpp.o
09:55:56  [ 40%] Building CXX object cudaaligner/CMakeFiles/cudaaligner.dir/src/ukkonen_cpu.cpp.o
09:55:56  [ 40%] Building CXX object cudaaligner/CMakeFiles/cudaaligner.dir/src/aligner_global_myers_banded.cpp.o
09:55:56  [ 40%] Building CXX object cudaaligner/CMakeFiles/cudaaligner.dir/src/aligner_global_hirschberg_myers.cpp.o
09:55:56  [ 42%] Building CXX object cudaaligner/CMakeFiles/cudaaligner.dir/src/needleman_wunsch_cpu.cpp.o
09:56:00  [ 43%] Linking CXX static library libcudaaligner.a
09:56:00  [ 43%] Built target cudaaligner
09:56:39  Scanning dependencies of target cudapoa
09:56:39  [ 45%] Building CXX object cudapoa/CMakeFiles/cudapoa.dir/src/cudapoa.cpp.o
09:56:39  [ 45%] Building CXX object cudapoa/CMakeFiles/cudapoa.dir/version.cpp.o
09:56:39  [ 45%] Linking CXX static library libcudapoa.a
09:56:39  [ 45%] Built target cudapoa
09:56:39  Makefile:162: recipe for target 'all' failed
09:56:39  make: *** [all] Error 2

Unfortunately, I cannot easily extract the Makefile for these builds as I am building singularity images in a build pipeline. 

Dominik

**Comment by EpiSlim** [comment]
Hi Dominik! The error message is not that explicit, but given your success with gcc8, my guess is that the issue is a cuda/gcc incompatibility problem. What distribution are you using for your builds and what version of CUDA do they include?

**Comment by ahehn-nv** [comment]
Hi Dominik. Did you build with `make -j ...`?
If so, could you try to run `make` in the build directory again without any arguments? I guess the actual error happened further up.

**Comment by dominik-handler** [comment]
Hi,

I am sorry but I cannot reproduce the error anymore. I now tried various variants of CUDA and gcc together and all of them build at the moment. 

Thank you in any case,
Dominik

**Comment by ahehn-nv** [comment]
No worries. The best issues are the ones that solve themselves. :)
