### ISSUE TITLE
Build fails with gcc 7 and 8

### ISSUE THREAD

**Issue by tristanpwdennis** [NVIDIA-Genomics-Research/GenomeWorks#663]
Hi!
I am attempting to build GenomeWorks but it crashes with the following errors.

After `make -j install`:

[ 44%] Built target cudapoa
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2

Then, I try just `make` and see this one (I also see ith with `make -j` but further up.

/home/dennistpw/packages/GenomeWorks/3rdparty/spoa/src/simd_alignment_engine.cpp:12:14: fatal error: immintrin.h: No such file or directory
     #include <immintrin.h> // AVX2 and lower
              ^~~~~~~~~~~~~
compilation terminated.
3rdparty/spoa/CMakeFiles/spoa.dir/build.make:110: recipe for target '3rdparty/spoa/CMakeFiles/spoa.dir/src/simd_alignment_engine.cpp.o' failed
make[2]: *** [3rdparty/spoa/CMakeFiles/spoa.dir/src/simd_alignment_engine.cpp.o] Error 1
CMakeFiles/Makefile2:413: recipe for target '3rdparty/spoa/CMakeFiles/spoa.dir/all' failed
make[1]: *** [3rdparty/spoa/CMakeFiles/spoa.dir/all] Error 2
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2

I saw on another issue that it may be compiler issue so I switch between gcc/g++ 7 and 8, and no luck.

I ran `make VERBOSE=1 2>&1 | tee verbose_build.log` and have attached the logs below if that would be more useful!

Versions:
- `Ubuntu 18.04.5 LTS (GNU/Linux 4.9.253-tegra aarch64)`
- `Python 3.6.9`
- `CUDA Version 10.2.300`
- `cmake version 3.10.2`
- GPU generation Volta
- autoconf and automake both installed

Any help would be greatly appreciated, thank you! :)

[verbose_build.log](https://github.com/clara-parabricks/GenomeWorks/files/7178957/verbose_build.log)

**Comment by EpiSlim** [comment]
Hi @tristanpwdennis, we only support x86 architectures for the moment. The Tegra SoC has an ARM CPU, which probably explains why the `immintrin.h` header was missing.
